#%RAML 1.0
title: ActiveMq

baseUri:
description: This API will fetch information from the ActiveMQ and store into the Database
version: v1



/Publish:
  post:
    responses:
      200:
        body:
          application/json:
            example: 

/Consume:
    get:
      responses:
        200:
          body:
            application/json:
              example: 


              
/Database:
  get:
    responses:
      200:
        body:
          application/json:
            example: 